global using AutoMapper;
global using FluentValidation;
global using MediatR;
global using NoteIt.Application.Common;
global using NoteIt.Application.Contracts.Persistence;
global using NoteIt.Application.Exceptions;
global using NoteIt.Application.Mappings;
global using NoteIt.Domain.Entities;
global using Microsoft.AspNetCore.Identity;
